apiVersion: core.choreo.dev/v1beta1
kind: ComponentConfig
spec:
  inbound:
    - name: Pizza-Shack API
      port: 8080
      type: REST
      networkVisibility: Public
      schemaFilePath: open-api.yaml